twig:
    default_path: '%kernel.project_dir%/templates'
    globals:  
        globalService: '@App\Service\GlobalService'
        globalCategories: '@App\Repository\CategoryRepository'
        globalActors: '@App\Repository\ActorRepository'




when@test:
    twig:
        strict_variables: true
